# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_main_window(object):
    def setupUi(self, main_window):
        if not main_window.objectName():
            main_window.setObjectName(u"main_window")
        main_window.setWindowModality(Qt.ApplicationModal)
        main_window.resize(1260, 700)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_window.sizePolicy().hasHeightForWidth())
        main_window.setSizePolicy(sizePolicy)
        main_window.setMinimumSize(QSize(1260, 700))
        main_window.setMaximumSize(QSize(1260, 700))
        font = QFont()
        font.setFamily(u"arial")
        main_window.setFont(font)
        self.pointcloudWidget = QWidget(main_window)
        self.pointcloudWidget.setObjectName(u"pointcloudWidget")
        self.pointcloudWidget.setEnabled(True)
        self.pointcloudWidget.setGeometry(QRect(840, 30, 400, 400))
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.pointcloudWidget.sizePolicy().hasHeightForWidth())
        self.pointcloudWidget.setSizePolicy(sizePolicy1)
        self.pointcloudWidget.setMinimumSize(QSize(400, 400))
        self.pointcloudWidget.setMaximumSize(QSize(400, 400))
        self.pointcloudWidget.setAutoFillBackground(False)
        self.pointcloudWidget.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.CamView = QLabel(main_window)
        self.CamView.setObjectName(u"CamView")
        self.CamView.setGeometry(QRect(20, 30, 400, 400))
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.CamView.sizePolicy().hasHeightForWidth())
        self.CamView.setSizePolicy(sizePolicy2)
        self.CamView.setMinimumSize(QSize(400, 400))
        self.CamView.setMaximumSize(QSize(400, 400))
        self.CamView.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.CamView.setFrameShape(QFrame.Box)
        self.CamView.setFrameShadow(QFrame.Raised)
        self.label = QLabel(main_window)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 10, 67, 17))
        self.label_2 = QLabel(main_window)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(430, 10, 81, 17))
        self.label_3 = QLabel(main_window)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(840, 10, 67, 17))
        self.lidar_frame = QFrame(main_window)
        self.lidar_frame.setObjectName(u"lidar_frame")
        self.lidar_frame.setGeometry(QRect(840, 30, 400, 400))
        self.lidar_frame.setMinimumSize(QSize(400, 400))
        self.lidar_frame.setMaximumSize(QSize(400, 400))
        self.lidar_frame.setAutoFillBackground(False)
        self.lidar_frame.setStyleSheet(u"")
        self.lidar_frame.setFrameShape(QFrame.Box)
        self.lidar_frame.setFrameShadow(QFrame.Raised)
        self.label_4 = QLabel(main_window)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 460, 67, 17))
        self.setting_frame = QFrame(main_window)
        self.setting_frame.setObjectName(u"setting_frame")
        self.setting_frame.setGeometry(QRect(20, 480, 1221, 201))
        self.setting_frame.setFrameShape(QFrame.Box)
        self.setting_frame.setFrameShadow(QFrame.Raised)
        self.setting_camera_label = QLabel(self.setting_frame)
        self.setting_camera_label.setObjectName(u"setting_camera_label")
        self.setting_camera_label.setGeometry(QRect(30, 5, 67, 17))
        self.frame_camera_setting = QFrame(self.setting_frame)
        self.frame_camera_setting.setObjectName(u"frame_camera_setting")
        self.frame_camera_setting.setGeometry(QRect(30, 25, 270, 165))
        self.frame_camera_setting.setFrameShape(QFrame.Box)
        self.frame_camera_setting.setFrameShadow(QFrame.Raised)
        self.camera_comboBox = QComboBox(self.frame_camera_setting)
        self.camera_comboBox.addItem("")
        self.camera_comboBox.addItem("")
        self.camera_comboBox.setObjectName(u"camera_comboBox")
        self.camera_comboBox.setGeometry(QRect(120, 10, 91, 25))
        self.camera_comboBox.setMaxVisibleItems(2)
        self.camera_ip_textedit = QPlainTextEdit(self.frame_camera_setting)
        self.camera_ip_textedit.setObjectName(u"camera_ip_textedit")
        self.camera_ip_textedit.setGeometry(QRect(60, 40, 191, 25))
        self.camera_ip_textedit.setFrameShadow(QFrame.Raised)
        self.camera_ip_textedit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.camera_ip_textedit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.camera_ip_textedit.setTabChangesFocus(True)
        self.camera_networkType_label = QLabel(self.frame_camera_setting)
        self.camera_networkType_label.setObjectName(u"camera_networkType_label")
        self.camera_networkType_label.setGeometry(QRect(10, 10, 101, 25))
        self.camera_ip_label = QLabel(self.frame_camera_setting)
        self.camera_ip_label.setObjectName(u"camera_ip_label")
        self.camera_ip_label.setGeometry(QRect(10, 40, 101, 25))
        self.camera_port_label = QLabel(self.frame_camera_setting)
        self.camera_port_label.setObjectName(u"camera_port_label")
        self.camera_port_label.setGeometry(QRect(10, 70, 101, 25))
        self.camera_topic_label = QLabel(self.frame_camera_setting)
        self.camera_topic_label.setObjectName(u"camera_topic_label")
        self.camera_topic_label.setEnabled(True)
        self.camera_topic_label.setGeometry(QRect(10, 100, 101, 25))
        self.camera_port_textedit = QPlainTextEdit(self.frame_camera_setting)
        self.camera_port_textedit.setObjectName(u"camera_port_textedit")
        self.camera_port_textedit.setGeometry(QRect(60, 70, 191, 25))
        self.camera_port_textedit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.camera_port_textedit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.camera_port_textedit.setTabChangesFocus(True)
        self.camera_port_textedit.setOverwriteMode(False)
        self.camera_topic_textedit = QPlainTextEdit(self.frame_camera_setting)
        self.camera_topic_textedit.setObjectName(u"camera_topic_textedit")
        self.camera_topic_textedit.setGeometry(QRect(60, 100, 191, 25))
        sizePolicy3 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.camera_topic_textedit.sizePolicy().hasHeightForWidth())
        self.camera_topic_textedit.setSizePolicy(sizePolicy3)
        self.camera_topic_textedit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.camera_topic_textedit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.camera_topic_textedit.setTabChangesFocus(True)
        self.camera_type_label = QLabel(self.frame_camera_setting)
        self.camera_type_label.setObjectName(u"camera_type_label")
        self.camera_type_label.setGeometry(QRect(10, 130, 67, 25))
        self.camera_type_textedit = QPlainTextEdit(self.frame_camera_setting)
        self.camera_type_textedit.setObjectName(u"camera_type_textedit")
        self.camera_type_textedit.setEnabled(True)
        self.camera_type_textedit.setGeometry(QRect(60, 130, 191, 25))
        sizePolicy3.setHeightForWidth(self.camera_type_textedit.sizePolicy().hasHeightForWidth())
        self.camera_type_textedit.setSizePolicy(sizePolicy3)
        font1 = QFont()
        font1.setPointSize(8)
        font1.setStyleStrategy(QFont.PreferAntialias)
        self.camera_type_textedit.setFont(font1)
        self.camera_type_textedit.setAutoFillBackground(True)
        self.camera_type_textedit.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.camera_type_textedit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.camera_type_textedit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.camera_type_textedit.setTabChangesFocus(True)
        self.camera_type_textedit.setReadOnly(True)
        self.camera_type_textedit.setTextInteractionFlags(Qt.NoTextInteraction)
        self.camera_type_textedit.setBackgroundVisible(False)
        self.frame_gps_setting = QFrame(self.setting_frame)
        self.frame_gps_setting.setObjectName(u"frame_gps_setting")
        self.frame_gps_setting.setGeometry(QRect(370, 25, 230, 165))
        self.frame_gps_setting.setFrameShape(QFrame.Box)
        self.frame_gps_setting.setFrameShadow(QFrame.Raised)
        self.gps_comboBox = QComboBox(self.frame_gps_setting)
        self.gps_comboBox.addItem("")
        self.gps_comboBox.addItem("")
        self.gps_comboBox.setObjectName(u"gps_comboBox")
        self.gps_comboBox.setGeometry(QRect(120, 10, 91, 25))
        self.gps_comboBox.setMaxVisibleItems(2)
        self.gps_ip_textedit = QPlainTextEdit(self.frame_gps_setting)
        self.gps_ip_textedit.setObjectName(u"gps_ip_textedit")
        self.gps_ip_textedit.setGeometry(QRect(60, 40, 151, 25))
        self.gps_ip_textedit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.gps_ip_textedit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.gps_ip_textedit.setTabChangesFocus(True)
        self.gps_networkType_label = QLabel(self.frame_gps_setting)
        self.gps_networkType_label.setObjectName(u"gps_networkType_label")
        self.gps_networkType_label.setGeometry(QRect(10, 10, 101, 25))
        self.gps_ip_label = QLabel(self.frame_gps_setting)
        self.gps_ip_label.setObjectName(u"gps_ip_label")
        self.gps_ip_label.setGeometry(QRect(10, 40, 101, 25))
        self.gps_port_label = QLabel(self.frame_gps_setting)
        self.gps_port_label.setObjectName(u"gps_port_label")
        self.gps_port_label.setGeometry(QRect(10, 70, 101, 25))
        self.gps_topic_label = QLabel(self.frame_gps_setting)
        self.gps_topic_label.setObjectName(u"gps_topic_label")
        self.gps_topic_label.setGeometry(QRect(10, 100, 101, 25))
        self.gps_port_textedit = QPlainTextEdit(self.frame_gps_setting)
        self.gps_port_textedit.setObjectName(u"gps_port_textedit")
        self.gps_port_textedit.setGeometry(QRect(60, 70, 151, 25))
        self.gps_port_textedit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.gps_port_textedit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.gps_port_textedit.setTabChangesFocus(True)
        self.gps_topic_textedit = QPlainTextEdit(self.frame_gps_setting)
        self.gps_topic_textedit.setObjectName(u"gps_topic_textedit")
        self.gps_topic_textedit.setGeometry(QRect(60, 100, 151, 25))
        self.gps_topic_textedit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.gps_topic_textedit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.gps_topic_textedit.setTabChangesFocus(True)
        self.gps_type_label = QLabel(self.frame_gps_setting)
        self.gps_type_label.setObjectName(u"gps_type_label")
        self.gps_type_label.setGeometry(QRect(10, 130, 101, 25))
        self.gps_type_textedit = QPlainTextEdit(self.frame_gps_setting)
        self.gps_type_textedit.setObjectName(u"gps_type_textedit")
        self.gps_type_textedit.setEnabled(True)
        self.gps_type_textedit.setGeometry(QRect(60, 130, 151, 25))
        font2 = QFont()
        font2.setPointSize(8)
        self.gps_type_textedit.setFont(font2)
        self.gps_type_textedit.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.gps_type_textedit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.gps_type_textedit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.gps_type_textedit.setTabChangesFocus(True)
        self.gps_type_textedit.setReadOnly(True)
        self.frame_imu_setting = QFrame(self.setting_frame)
        self.frame_imu_setting.setObjectName(u"frame_imu_setting")
        self.frame_imu_setting.setGeometry(QRect(660, 25, 230, 165))
        self.frame_imu_setting.setFrameShape(QFrame.Box)
        self.frame_imu_setting.setFrameShadow(QFrame.Raised)
        self.imu_comboBox = QComboBox(self.frame_imu_setting)
        self.imu_comboBox.addItem("")
        self.imu_comboBox.addItem("")
        self.imu_comboBox.setObjectName(u"imu_comboBox")
        self.imu_comboBox.setGeometry(QRect(120, 10, 91, 25))
        self.imu_comboBox.setMaxVisibleItems(2)
        self.imu_ip_textedit = QPlainTextEdit(self.frame_imu_setting)
        self.imu_ip_textedit.setObjectName(u"imu_ip_textedit")
        self.imu_ip_textedit.setGeometry(QRect(60, 40, 151, 25))
        self.imu_ip_textedit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.imu_ip_textedit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.imu_ip_textedit.setTabChangesFocus(True)
        self.imu_networkType_label = QLabel(self.frame_imu_setting)
        self.imu_networkType_label.setObjectName(u"imu_networkType_label")
        self.imu_networkType_label.setGeometry(QRect(10, 10, 101, 25))
        self.imu_ip_label = QLabel(self.frame_imu_setting)
        self.imu_ip_label.setObjectName(u"imu_ip_label")
        self.imu_ip_label.setGeometry(QRect(10, 40, 101, 25))
        self.imu_port_label = QLabel(self.frame_imu_setting)
        self.imu_port_label.setObjectName(u"imu_port_label")
        self.imu_port_label.setGeometry(QRect(10, 70, 101, 25))
        self.imu_topic_label = QLabel(self.frame_imu_setting)
        self.imu_topic_label.setObjectName(u"imu_topic_label")
        self.imu_topic_label.setEnabled(True)
        self.imu_topic_label.setGeometry(QRect(10, 100, 101, 25))
        self.imu_port_textedit = QPlainTextEdit(self.frame_imu_setting)
        self.imu_port_textedit.setObjectName(u"imu_port_textedit")
        self.imu_port_textedit.setGeometry(QRect(60, 70, 151, 25))
        self.imu_port_textedit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.imu_port_textedit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.imu_port_textedit.setTabChangesFocus(True)
        self.imu_topic_textedit = QPlainTextEdit(self.frame_imu_setting)
        self.imu_topic_textedit.setObjectName(u"imu_topic_textedit")
        self.imu_topic_textedit.setEnabled(True)
        self.imu_topic_textedit.setGeometry(QRect(60, 100, 151, 25))
        self.imu_topic_textedit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.imu_topic_textedit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.imu_topic_textedit.setTabChangesFocus(True)
        self.imu_type_label = QLabel(self.frame_imu_setting)
        self.imu_type_label.setObjectName(u"imu_type_label")
        self.imu_type_label.setGeometry(QRect(10, 130, 101, 25))
        self.imu_type_textedit = QPlainTextEdit(self.frame_imu_setting)
        self.imu_type_textedit.setObjectName(u"imu_type_textedit")
        self.imu_type_textedit.setEnabled(True)
        self.imu_type_textedit.setGeometry(QRect(60, 130, 151, 25))
        font3 = QFont()
        font3.setPointSize(9)
        self.imu_type_textedit.setFont(font3)
        self.imu_type_textedit.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.imu_type_textedit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.imu_type_textedit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.imu_type_textedit.setTabChangesFocus(True)
        self.imu_type_textedit.setReadOnly(True)
        self.frame_lidar_setting = QFrame(self.setting_frame)
        self.frame_lidar_setting.setObjectName(u"frame_lidar_setting")
        self.frame_lidar_setting.setGeometry(QRect(960, 25, 230, 165))
        self.frame_lidar_setting.setFrameShape(QFrame.Box)
        self.frame_lidar_setting.setFrameShadow(QFrame.Raised)
        self.lidar_comboBox = QComboBox(self.frame_lidar_setting)
        self.lidar_comboBox.addItem("")
        self.lidar_comboBox.addItem("")
        self.lidar_comboBox.setObjectName(u"lidar_comboBox")
        self.lidar_comboBox.setGeometry(QRect(120, 10, 91, 25))
        self.lidar_comboBox.setMaxVisibleItems(2)
        self.lidar_ip_textedit = QPlainTextEdit(self.frame_lidar_setting)
        self.lidar_ip_textedit.setObjectName(u"lidar_ip_textedit")
        self.lidar_ip_textedit.setGeometry(QRect(60, 40, 151, 25))
        self.lidar_ip_textedit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lidar_ip_textedit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lidar_ip_textedit.setTabChangesFocus(True)
        self.lidar_networkType_label = QLabel(self.frame_lidar_setting)
        self.lidar_networkType_label.setObjectName(u"lidar_networkType_label")
        self.lidar_networkType_label.setGeometry(QRect(10, 10, 101, 25))
        self.lidar_ip_label = QLabel(self.frame_lidar_setting)
        self.lidar_ip_label.setObjectName(u"lidar_ip_label")
        self.lidar_ip_label.setGeometry(QRect(10, 40, 101, 25))
        self.lidar_port_label = QLabel(self.frame_lidar_setting)
        self.lidar_port_label.setObjectName(u"lidar_port_label")
        self.lidar_port_label.setGeometry(QRect(10, 70, 101, 25))
        self.lidar_topic_label = QLabel(self.frame_lidar_setting)
        self.lidar_topic_label.setObjectName(u"lidar_topic_label")
        self.lidar_topic_label.setGeometry(QRect(10, 100, 101, 25))
        self.lidar_port_textedit = QPlainTextEdit(self.frame_lidar_setting)
        self.lidar_port_textedit.setObjectName(u"lidar_port_textedit")
        self.lidar_port_textedit.setGeometry(QRect(60, 70, 151, 25))
        self.lidar_port_textedit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lidar_port_textedit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lidar_port_textedit.setTabChangesFocus(True)
        self.lidar_topic_textedit = QPlainTextEdit(self.frame_lidar_setting)
        self.lidar_topic_textedit.setObjectName(u"lidar_topic_textedit")
        self.lidar_topic_textedit.setGeometry(QRect(60, 100, 151, 25))
        self.lidar_topic_textedit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lidar_topic_textedit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lidar_topic_textedit.setTabChangesFocus(True)
        self.lidar_type_label = QLabel(self.frame_lidar_setting)
        self.lidar_type_label.setObjectName(u"lidar_type_label")
        self.lidar_type_label.setGeometry(QRect(10, 130, 101, 25))
        self.lidar_type_textedit = QPlainTextEdit(self.frame_lidar_setting)
        self.lidar_type_textedit.setObjectName(u"lidar_type_textedit")
        self.lidar_type_textedit.setGeometry(QRect(60, 130, 151, 25))
        self.lidar_type_textedit.setFont(font2)
        self.lidar_type_textedit.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.lidar_type_textedit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lidar_type_textedit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lidar_type_textedit.setTabChangesFocus(True)
        self.lidar_type_textedit.setReadOnly(True)
        self.setting_gps_label = QLabel(self.setting_frame)
        self.setting_gps_label.setObjectName(u"setting_gps_label")
        self.setting_gps_label.setGeometry(QRect(370, 5, 67, 17))
        self.setting_imu_label = QLabel(self.setting_frame)
        self.setting_imu_label.setObjectName(u"setting_imu_label")
        self.setting_imu_label.setGeometry(QRect(660, 5, 67, 17))
        self.setting_lidar_label = QLabel(self.setting_frame)
        self.setting_lidar_label.setObjectName(u"setting_lidar_label")
        self.setting_lidar_label.setGeometry(QRect(960, 5, 67, 17))
        self.ConnectButton = QPushButton(main_window)
        self.ConnectButton.setObjectName(u"ConnectButton")
        self.ConnectButton.setGeometry(QRect(1080, 440, 161, 31))
        self.MapView = QGraphicsView(main_window)
        self.MapView.setObjectName(u"MapView")
        self.MapView.setGeometry(QRect(430, 30, 400, 400))
        sizePolicy2.setHeightForWidth(self.MapView.sizePolicy().hasHeightForWidth())
        self.MapView.setSizePolicy(sizePolicy2)
        self.MapView.setMinimumSize(QSize(400, 400))
        self.MapView.setMaximumSize(QSize(400, 400))
        self.MapView.setFocusPolicy(Qt.NoFocus)
        self.MapView.setAcceptDrops(False)
        self.MapView.setFrameShape(QFrame.Box)
        self.MapView.setFrameShadow(QFrame.Raised)
        self.MapView.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.MapView.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.MapView.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)

        self.retranslateUi(main_window)

        QMetaObject.connectSlotsByName(main_window)
    # setupUi

    def retranslateUi(self, main_window):
        main_window.setWindowTitle(QCoreApplication.translate("main_window", u"MORAI Sensor Viewer", None))
        self.CamView.setText("")
        self.label.setText(QCoreApplication.translate("main_window", u"Camera", None))
        self.label_2.setText(QCoreApplication.translate("main_window", u"GPS & IMU", None))
        self.label_3.setText(QCoreApplication.translate("main_window", u"LiDAR", None))
        self.label_4.setText(QCoreApplication.translate("main_window", u"Setting", None))
        self.setting_camera_label.setText(QCoreApplication.translate("main_window", u"Camera", None))
        self.camera_comboBox.setItemText(0, QCoreApplication.translate("main_window", u"UDP", None))
        self.camera_comboBox.setItemText(1, QCoreApplication.translate("main_window", u"ROS", None))

        self.camera_comboBox.setCurrentText(QCoreApplication.translate("main_window", u"UDP", None))
        self.camera_ip_textedit.setPlainText(QCoreApplication.translate("main_window", u"127.0.0.1", None))
        self.camera_networkType_label.setText(QCoreApplication.translate("main_window", u"Network Type :", None))
        self.camera_ip_label.setText(QCoreApplication.translate("main_window", u"IP : ", None))
        self.camera_port_label.setText(QCoreApplication.translate("main_window", u"Port : ", None))
        self.camera_topic_label.setText(QCoreApplication.translate("main_window", u"Topic : ", None))
        self.camera_port_textedit.setPlainText(QCoreApplication.translate("main_window", u"1232", None))
        self.camera_topic_textedit.setPlainText(QCoreApplication.translate("main_window", u"/image_jpeg/compressed", None))
        self.camera_type_label.setText(QCoreApplication.translate("main_window", u"Type : ", None))
        self.camera_type_textedit.setPlainText(QCoreApplication.translate("main_window", u"sensor_msgs/CompressedImage", None))
        self.gps_comboBox.setItemText(0, QCoreApplication.translate("main_window", u"UDP", None))
        self.gps_comboBox.setItemText(1, QCoreApplication.translate("main_window", u"ROS", None))

        self.gps_comboBox.setCurrentText(QCoreApplication.translate("main_window", u"UDP", None))
        self.gps_ip_textedit.setPlainText(QCoreApplication.translate("main_window", u"127.0.0.1", None))
        self.gps_networkType_label.setText(QCoreApplication.translate("main_window", u"Network Type :", None))
        self.gps_ip_label.setText(QCoreApplication.translate("main_window", u"IP : ", None))
        self.gps_port_label.setText(QCoreApplication.translate("main_window", u"Port : ", None))
        self.gps_topic_label.setText(QCoreApplication.translate("main_window", u"Topic : ", None))
        self.gps_port_textedit.setPlainText(QCoreApplication.translate("main_window", u"1234", None))
        self.gps_topic_textedit.setPlainText(QCoreApplication.translate("main_window", u"/gps", None))
        self.gps_type_label.setText(QCoreApplication.translate("main_window", u"Type : ", None))
        self.gps_type_textedit.setPlainText(QCoreApplication.translate("main_window", u"morai_msgs/GPSMessage", None))
        self.imu_comboBox.setItemText(0, QCoreApplication.translate("main_window", u"UDP", None))
        self.imu_comboBox.setItemText(1, QCoreApplication.translate("main_window", u"ROS", None))

        self.imu_comboBox.setCurrentText(QCoreApplication.translate("main_window", u"UDP", None))
        self.imu_ip_textedit.setPlainText(QCoreApplication.translate("main_window", u"127.0.0.1", None))
        self.imu_networkType_label.setText(QCoreApplication.translate("main_window", u"Network Type :", None))
        self.imu_ip_label.setText(QCoreApplication.translate("main_window", u"IP : ", None))
        self.imu_port_label.setText(QCoreApplication.translate("main_window", u"Port : ", None))
        self.imu_topic_label.setText(QCoreApplication.translate("main_window", u"Topic : ", None))
        self.imu_port_textedit.setPlainText(QCoreApplication.translate("main_window", u"1236", None))
        self.imu_topic_textedit.setPlainText(QCoreApplication.translate("main_window", u"/imu", None))
        self.imu_type_label.setText(QCoreApplication.translate("main_window", u"Type : ", None))
        self.imu_type_textedit.setPlainText(QCoreApplication.translate("main_window", u"sensor_msgs/Imu", None))
        self.lidar_comboBox.setItemText(0, QCoreApplication.translate("main_window", u"UDP", None))
        self.lidar_comboBox.setItemText(1, QCoreApplication.translate("main_window", u"ROS", None))

        self.lidar_comboBox.setCurrentText(QCoreApplication.translate("main_window", u"UDP", None))
        self.lidar_ip_textedit.setPlainText(QCoreApplication.translate("main_window", u"127.0.0.1", None))
        self.lidar_networkType_label.setText(QCoreApplication.translate("main_window", u"Network Type :", None))
        self.lidar_ip_label.setText(QCoreApplication.translate("main_window", u"IP : ", None))
        self.lidar_port_label.setText(QCoreApplication.translate("main_window", u"Port : ", None))
        self.lidar_topic_label.setText(QCoreApplication.translate("main_window", u"Topic : ", None))
        self.lidar_port_textedit.setPlainText(QCoreApplication.translate("main_window", u"2368", None))
        self.lidar_topic_textedit.setPlainText(QCoreApplication.translate("main_window", u"/velodyne_points", None))
        self.lidar_type_label.setText(QCoreApplication.translate("main_window", u"Type : ", None))
        self.lidar_type_textedit.setPlainText(QCoreApplication.translate("main_window", u"sensor_msgs/PointCloud2", None))
        self.setting_gps_label.setText(QCoreApplication.translate("main_window", u"GPS", None))
        self.setting_imu_label.setText(QCoreApplication.translate("main_window", u"IMU", None))
        self.setting_lidar_label.setText(QCoreApplication.translate("main_window", u"LiDAR", None))
        self.ConnectButton.setText(QCoreApplication.translate("main_window", u"Connect", None))
    # retranslateUi

